# https://www.youtube.com/watch?v=uFcXrWT4f80
name: Run tests

on:
  pull_request:
    branches: ['master']
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: test
        run:
          cd test
          pytest